"""Regenerate app/emoji/catalog.tsv: the emoji the server may suggest, with their Russian
and English names and keywords from Unicode CLDR.

    uv run python scripts/emoji_catalog.py

Kept: fully-qualified emoji up to MAX_VERSION (iOS 17 draws Emoji 15.0), without skin tones
or gendered duplicates. Dropped: groups that match task words by accident and never make
a task's icon (keycaps, clock faces, zodiac, CJK buttons, arrows, most country flags).
Task phrases for the emoji live separately, in app/emoji/aliases.txt.
"""

import json
import re
import urllib.request
from pathlib import Path

CLDR = "46.0.0"
EMOJI_TEST = "https://unicode.org/Public/emoji/15.1/emoji-test.txt"
ANNOTATIONS = [
    "https://cdn.jsdelivr.net/npm/cldr-annotations-full@{cldr}/annotations/{lang}/annotations.json",
    "https://cdn.jsdelivr.net/npm/cldr-annotations-derived-full@{cldr}/annotationsDerived/{lang}/annotations.json",
]
# Russian decides which emoji are in (an emoji without a Russian name is left out);
# English adds a second description to the same emoji.
LANGS = ["ru", "en"]
MAX_VERSION = 15.0
OUT = Path(__file__).resolve().parents[1] / "app" / "emoji" / "catalog.tsv"

DROP_SUBGROUPS = {
    "alphanum", "arrow", "av-symbol", "country-flag", "currency", "family", "gender",
    "geometric", "keycap", "math", "person-fantasy", "punctuation", "religion",
    "subdivision-flag", "transport-sign", "warning", "zodiac",
}  # fmt: skip
# Worth keeping from the dropped subgroups: symbols that do name a task, flags of languages
# people study.
KEEP = set(
    "🆕 🆗 🆘 🆓 🔤 🔢 🛜 📶 🚮 🚰 🚼 🚸 ⚠️ 🚫 ♾️ "
    "🇬🇧 🇺🇸 🇯🇵 🇨🇳 🇩🇪 🇫🇷 🇪🇸 🇮🇹 🇰🇷 🇹🇷 🇷🇺 🇺🇦 🇵🇹 🇧🇷 🇮🇳 🇬🇪 🇦🇲 🇰🇿 🇮🇱 🇵🇱 "
    "🇳🇱 🇬🇷 🇹🇭 🇻🇳 🇦🇪 🇪🇬 🇨🇦 🇲🇽 🇷🇸 🇫🇮 🇸🇪".split()
)
SKIN_TONES = {chr(c) for c in range(0x1F3FB, 0x1F400)}
CLOCK_FACES = {chr(c) for c in range(0x1F550, 0x1F568)}
ZWJ = "‍"
LINE = re.compile(r"^[0-9A-F ]+;\s*(\S+)\s*#\s*(\S+)\s+E(\d+\.\d+)\s")


def fetch(url: str) -> str:
    with urllib.request.urlopen(url, timeout=60) as resp:
        return resp.read().decode()


def emoji_list() -> list[tuple[str, str]]:
    """(emoji, subgroup) in Unicode order."""
    out, group, subgroup = [], "", ""
    for line in fetch(EMOJI_TEST).splitlines():
        if line.startswith("# group:"):
            group = line.split(":", 1)[1].strip()
        elif line.startswith("# subgroup:"):
            subgroup = line.split(":", 1)[1].strip()
        elif (m := LINE.match(line)) and group != "Component":
            status, emoji, version = m.groups()
            if status == "fully-qualified" and float(version) <= MAX_VERSION:
                out.append((emoji, subgroup))
    return out


def keep(emoji: str, subgroup: str) -> bool:
    if emoji in KEEP:
        return True
    if subgroup in DROP_SUBGROUPS or emoji in CLOCK_FACES:
        return False
    if any(ch in SKIN_TONES for ch in emoji):
        return False
    # 👨‍⚕️ and 👩‍⚕️ next to 🧑‍⚕️, 🏊‍♀️ next to 🏊: the same suggestion three times.
    return not (ZWJ in emoji and ("♂" in emoji or "♀" in emoji or emoji[0] in "👨👩"))


def annotations(lang: str) -> dict[str, dict]:
    out = {}
    for url in ANNOTATIONS:
        data = json.loads(fetch(url.format(cldr=CLDR, lang=lang)))
        body = data.get("annotations") or data["annotationsDerived"]
        for key, value in body["annotations"].items():
            out[key.replace("️", "")] = value
    return out


def columns(ann: dict | None) -> list[str]:
    """Name and keywords, or two empty columns."""
    if not ann or not ann.get("tts"):
        return ["", ""]
    keywords = [k for k in ann.get("default", []) if "\t" not in k]
    return [ann["tts"][0], " | ".join(keywords)]


def main() -> None:
    names = {lang: annotations(lang) for lang in LANGS}
    rows = []
    for emoji, subgroup in emoji_list():
        if not keep(emoji, subgroup):
            continue
        cols = [columns(names[lang].get(emoji.replace("️", ""))) for lang in LANGS]
        if not cols[0][0]:
            continue
        rows.append("\t".join([emoji, *(c for pair in cols for c in pair)]))
    header = (
        f"# Generated by scripts/emoji_catalog.py from Unicode CLDR {CLDR} annotations\n"
        "# (ru, en) and emoji-test.txt; Unicode License v3.\n"
        "# emoji <TAB> ru name <TAB> ru keywords <TAB> en name <TAB> en keywords\n"
    )
    OUT.write_text(header + "\n".join(rows) + "\n")
    print(f"Wrote {len(rows)} emoji to {OUT}")


if __name__ == "__main__":
    main()
